### PR TITLE
Closeable minimap

### PR DESCRIPTION
**Pull request by Tehsurfer**

### CODE REVIEW

**Comment by alan-wu** [comment]
I think the correct way to approach this is to add an api to hide/show the minimap in this code base and add the close/open button on FlatmapVuer.

By the way, this repos is out-of-date and has been moved to here - https://github.com/AnatomicMaps/flatmap-viewer.

**Comment by dbrnz** [comment]
There is no need to add anything to the flatmap-viewer code as it already contains an API method to show/hide the minimap (see around line 730 of ‘flatmap-viewer.js’.Sent from my iPhoneOn 13/02/2023, at 10:59 AM, Alan Wu ***@***.***> wrote:﻿
I think the correct way to approach this is to add an api to hide/show the minimap in this code base and add the close/open button on FlatmapVuer.
By the way, this repos is out-of-date and has been moved to here - https://github.com/AnatomicMaps/flatmap-viewer.

**Comment by Tehsurfer** [comment]
Oops sorry guys I didn't realise this had moved locations!

Do we still need this repo?

**Comment by dbrnz** [comment]
No!Sent from my iPhoneOn 14/02/2023, at 2:08 PM, Jesse Khorasanee ***@***.***> wrote:﻿
Oops sorry guys I didn't realise this had moved locations!
Do we still need this repo?

**Comment by Tehsurfer** [comment]
Ok cool in that case, @alan-wu and @dbrnz how would you feel about archiving this repo?

(So that we don't accidentally try and add code to it)

**Comment by dbrnz** [comment]
Archive or delete is fine by me.

**Pull request closed without merging**
